# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uploads_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15uploads_service.proto\x12\x07uploads\x1a\x1bgoogle/protobuf/empty.proto\"*\n\x0c\x43laimFileReq\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x62ucket\x18\x02 \x01(\t\"h\n\rClaimFileResp\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04mime\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x0c\n\x04size\x18\x04 \x01(\x03\x12\r\n\x05width\x18\x05 \x01(\x05\x12\x0e\n\x06height\x18\x06 \x01(\x05\"\x1b\n\rDeleteFileReq\x12\n\n\x02id\x18\x01 \x01(\t\" \n\rClearFilesReq\x12\x0f\n\x07user_id\x18\x01 \x01(\t2\xc1\x01\n\x07Uploads\x12:\n\tClaimFile\x12\x15.uploads.ClaimFileReq\x1a\x16.uploads.ClaimFileResp\x12<\n\nDeleteFile\x12\x16.uploads.DeleteFileReq\x1a\x16.google.protobuf.Empty\x12<\n\nClearFiles\x12\x16.uploads.ClearFilesReq\x1a\x16.google.protobuf.EmptyB\x04Z\x02./b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uploads_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\002./'
  _globals['_CLAIMFILEREQ']._serialized_start=63
  _globals['_CLAIMFILEREQ']._serialized_end=105
  _globals['_CLAIMFILERESP']._serialized_start=107
  _globals['_CLAIMFILERESP']._serialized_end=211
  _globals['_DELETEFILEREQ']._serialized_start=213
  _globals['_DELETEFILEREQ']._serialized_end=240
  _globals['_CLEARFILESREQ']._serialized_start=242
  _globals['_CLEARFILESREQ']._serialized_end=274
  _globals['_UPLOADS']._serialized_start=277
  _globals['_UPLOADS']._serialized_end=470
# @@protoc_insertion_point(module_scope)
